### ISSUE TITLE
Acceptance if response exceeds capacity

### ISSUE THREAD

**Issue by braughtg** [computing-in-the-liberal-arts/SIGCSE2020-PreSymposium-Event#13]
@HollandMinkley @henry-walker @ProfJanetDavis @DougBaldwin 

There is no language in the call for participation for the contingency in which the response exceeds the capacity of the venue.  This may not happen, but perhaps a sentence addressing the possibility that we will need to be selective about invitations should be in the CFP? 

Thoughts?  Any suggested language or placement in the CFP?

**Comment by DougBaldwin** [comment]
I don't expect that we'll run out of room, but I could be wrong (there was a lot of interest in the liberal arts special sessions after all). It's probably worth having language in the call that acknowledges the possibility, but not worth worrying about making it very detailed or 100% "right." Maybe just say that if registrations exceed room capacity, priority will be given to people presenting examples or challenges, or something similar (where the reality might be that we do that, plus first-come-first-served if presenters-first doesn't resolve the whole problem, and maybe other considerations -- this is where we should be ready to create some policy if we need it, but the odds of needing it seem slim to me).

Do we know what our capacity will be?

**Comment by HollandMinkley** [comment]
I had much the same thought as Doug in terms of language - giving preference to people presenting examples or challenges, plus maybe saying we'll also prioritize having attendees from as many institutions as possible (so if we have to cut off participation, not having three people from the same school attend). Beyond that we can look at what they say about their interest in attending to try to get good breadth.

Not sure I love this language but maybe something like "In the event we receive more applications to attend than our room capacity, attendees will be selected giving first priority to those presenting examples or challenges and then reviewing attendance applications to achieve representation from a broad range of institutions."  That last phrase gives us some flexibility to also make sure we've got people with different teaching loads, faculty sizes, etc.

**Comment by henry-walker** [comment]
Two thoughts.

1.  Would we have an option for a bigger room, if needed?  Often conference leadership has a range of options they need to juggle, and we might be able to move (or maybe not).
2.  I think we need to be careful not to discourage folks from applying, if they think this might fill up.  I'm not sure how to do that, but Amanda's sentence might begin, "In the UNEXPECTED event we receive ... ."

Henry

-----

Henry M. Walker

Samuel R. and Marie-Louise Rosenthal
    Professor of Natural Science
    and Mathematics
Professor of Computer Science
Noyce Science Center
1116 8th Avenue
Grinnell College
Grinnell, IA  50112-1690
United States of America
+1 641-269-4208
Fax:  +1 641-269-4984
http://www.cs.grinnell.edu/~walker/

**Comment by braughtg** [comment]
Combining Amanda's and Henry's ideas, how about the following?

"We anticipate being able to invite everyone who expresses interest.  However, in the unlikely event that our venue cannot accommodate everyone, attendees will be selected giving first priority to those presenting examples or challenges and then reviewing attendance applications to achieve representation from a broad range of institutions."

**Comment by henry-walker** [comment]
Very nice!

Henry

-----

Henry M. Walker

Samuel R. and Marie-Louise Rosenthal
    Professor of Natural Science
    and Mathematics
Professor of Computer Science
Noyce Science Center
1116 8th Avenue
Grinnell College
Grinnell, IA  50112-1690
United States of America
+1 641-269-4208
Fax:  +1 641-269-4984
http://www.cs.grinnell.edu/~walker/

**Comment by DougBaldwin** [comment]
Looks fine to me. Thanks.

Doug Baldwin

**Comment by HollandMinkley** [comment]
I like this wording also - good with me!

**Comment by braughtg** [comment]
Added the text below to the CFP:

> "We anticipate being able to invite everyone who expresses interest. However, in the unlikely event that our venue cannot accommodate everyone, attendees will be selected giving first priority to those presenting examples or challenges and then reviewing attendance applications to achieve representation from a broad range of institutions."

Closes #13
