### ISSUE TITLE
Challenges Example

### ISSUE THREAD

**Issue by braughtg** [computing-in-the-liberal-arts/SIGCSE2020-PreSymposium-Event#4]
Need to create an example of a challenges, opportunities, and possible organizational directions submission and update links in CallForParticpation.md

**Comment by braughtg** [comment]
I have a model from Amanda that she sent me via e-mail.  I will generate a PR and merge it later today.

**Comment by ProfJanetDavis** [comment]
I have two questions about the examples of challenges currently in our repository.

- IIRC, both were written by @HollandMinkley. Is there a reason doesn't want to be credited for them? It seems not too unlikely we could end up discussing one or both at the event, and I'd like to give credit where it's due.
- Is an institutional context strictly necessary for these challenges? If not, we might simplify by taking that section out. 

I'm sorry I didn't raise these questions when these examples were first put on GitHub - it didn't occur to me until responding to a recent question from Grant about making submissions find-able.

**Comment by braughtg** [comment]
I agree.  We should list Amanda as the Author of those examples.  That was a mistake on my part. 

I think the institutional context could be worthwhile in that some issues/challenges/opportunities may be more relevant at one place than another.  Happy to be convinced that simplification of the process outweighs this possibility 

Do you have time to do the updates?  Or would you like me to have a go?

**Comment by braughtg** [comment]
I went ahead and made some of the changes, added Amanda as the author and asked her for the rest of the institutional context.  I will paste that in when she replies.
