### ISSUE TITLE
E-Mail Address for Submissions via e-mail

### ISSUE THREAD

**Issue by braughtg** [computing-in-the-liberal-arts/SIGCSE2020-PreSymposium-Event#5]
Need to identify e-mail address for submissions being made by e-mail rather than by pull request.  Then need to update the address in CallForParticpation.md

**Comment by ProfJanetDavis** [comment]
I'm willing to do this, unless you think we should get a new address for the event (e.g., on GMail).

**Comment by braughtg** [comment]
> I'm willing to do this, unless you think we should get a new address for the event (e.g., on GMail).

@ProfJanetDavis Happy to have you do it.  Please update the Call For Proposals with the address you would like to use.

**Comment by braughtg** [comment]
Thanks @ProfJanetDavis!  When the time comes and these start coming in I'll be happy to do some of the conversions from whatever to markdown and PRs.
