### ISSUE TITLE
Check Dates for Submissions and Notifications

### ISSUE THREAD

**Issue by braughtg** [computing-in-the-liberal-arts/SIGCSE2020-PreSymposium-Event#6]
Check the dates in the Call for Participation to ensure that they make sense.  We can discuss and adapt based on everyone's thoughts.  Please discuss in this thread.

**Comment by ProfJanetDavis** [comment]
@braughtg proposed a submission deadline of January 10 and a notification date of January 24. I don't have any particular problems with those dates.

**Comment by braughtg** [comment]
At this point I'm assuming these dates are good and closing this.
