### ISSUE TITLE
Arrange room reservation

### ISSUE THREAD

**Issue by ProfJanetDavis** [computing-in-the-liberal-arts/SIGCSE2020-PreSymposium-Event#9]
The [call for proposals](https://sigcse2020.sigcse.org/authors/presymposium.html) says the charge for a half-day event is $325. We don't yet know when we'll be called upon to pay the fee or asked about our meeting room needs.

**Comment by braughtg** [comment]
This has been paid. But then an e-mail from Laurie Murphy on behalf of SIGCSE said "As a subcommittee of SIGCSE, we would not charge the room fee ($325) to this event for this first time."  A reply asking if our payments could be credited back has not received a reply.
